### ISSUE TITLE
Missing background color in buttons

### ISSUE THREAD

**Issue by Silvano14** [krupinskij/react-pdf-printer#39]
![Screenshot from 2024-02-12 14-04-05](https://github.com/krupinskij/react-pdf-printer/assets/48119437/f9822978-163d-4ae3-83e0-774142b377ac)

As you can see, I've added a simple test button. However, when I create a PDF file, the background color doesn't appear in the PDF.

The PDF can be found here: [HR-Platform-1.pdf](https://github.com/krupinskij/react-pdf-printer/files/14238646/HR-Platform-1.pdf)

I'm using the following style libraries: Chakra, Tailwind.

**Comment by krupinskij** [comment]
Hi.
On your browser printer modal see if "Background graphics" checkbox is checked. If not, check it and see if it helps.
![obraz](https://github.com/krupinskij/react-pdf-printer/assets/50505013/b60bc886-184f-4242-af59-8c99f4b42c96)
Next make sure if style.css file is included is some general stylesheet like here [LINK](https://github.com/krupinskij/react-pdf-printer-example/blob/master/src/index.css#L1)
This stylesheet should check this option or even remove it from this modal.

**Comment by Silvano14** [comment]
Hi there!

You're absolutely correct. If I check the checkbox, I can see the background. I have a question though: why is it that in your example project, I can see the background color without checking the box? Is there perhaps a default value that automatically checks the box?

Thank you for your assistance!

**Comment by Silvano14** [comment]
Perfect, thank you very much!
